### ISSUE TITLE
[Rus] Нафиг всё лагает

### ISSUE THREAD

**Issue by KotRikD** [SGezha/yomp#15]
**Шаги воспроизведения:**
1. Открываем YOMP
2. Запускаем импорт osu песен
3. Пытаемся зайти в ютуб и осознать что происходит

**ФР:** 
Пишем в поиск что-либо, получаем зависание и возможность не выдачи

**ОР:**
Всё прекрасно работает

**Comment by SGezha** [comment]
¯\_(ツ)_/¯
