### ISSUE TITLE
[Rus] Зачем нужна кнопка 'Import Folders'?

### ISSUE THREAD

**Issue by KotRikD** [SGezha/yomp#16]
**Шаги воспроизведения:**
1. Открываем YOMP
2. Открываем гамбургер слева и кликаем Import Folder
3. Думаем, как типичный пользователь и скорее всего эта фигня значит относится к поиску обычного музла

**ФР:**
При нажатии плеер сворачивает в маленькое окошко, не понятно что обозначающее.

**ОР:**
Что-то должно происходить

![image](https://user-images.githubusercontent.com/23283658/65833391-aa54ac80-e2d8-11e9-98bc-96fd4a0579db.png)

**Comment by SGezha** [comment]
Для импорта mp3 файлов из папки. Баг на скриншоте пофиксен!
