### ISSUE TITLE
Bottom panel is not working(1.0.4 Portable)

### ISSUE THREAD

**Issue by uzervlad** [SGezha/yomp#7]
It is possible to seek using progress bar, but it doesn't move itself. Elasped time is not working either.

**Comment by uzervlad** [comment]
That's why you should've used Sequelize
![image](https://user-images.githubusercontent.com/24654479/65721629-0f2ebd80-e0b3-11e9-8e3f-36c539ec8250.png)

**Comment by uzervlad** [comment]
After pressing "shuffle" button, YOMP doesn't work at all. I import my osu! songs, but they don't appear in the app

**Comment by uzervlad** [comment]
The bug disappeared after I restarted the app(with setup this time)

**Comment by SGezha** [comment]
FIXED
