### ISSUE TITLE
[?] Song object is working really weird

### ISSUE THREAD

**Issue by uzervlad** [SGezha/yomp#9]
So, when the song starts, the object(`<div>`) is highlighted. But when the song is paused OR the screen is changed(i.e. to "Loved") highlight is taken off.

**Comment by SGezha** [comment]
Over the weekend, I will completely rewrite the player on VUE. Because my "last year" code works terribly ;c

**Comment by uzervlad** [comment]
Honestly, it also looks like trash, try making it modular and never ever ever ever make all in functions. Create classes, they are much easier to work with.
I would also recommend moving all the job to main process and let renderer process only do the rendering.

**Comment by uzervlad** [comment]
Any reason for closing this issue?
